paths:
  /api/products/:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos fueron obtenidos correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "401":
          description: Error por falta de permisos
        "500":
          description: Error interno del servidor

    post:
      summary: Agregar un nuevo producto
      tags:
        - Productos
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: El producto fue agregado correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "401":
          description: Error por falta de permisos
        "500":
          description: Error interno del servidor

  /api/products/{id}:
    get:
      summary: Obtener un producto por su ID
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: El producto fue obtenido correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "401":
          description: Error por falta de permisos
        "500":
          description: Error interno del servidor

    put:
      summary: Actualizar un producto por su ID
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "200":
          description: El producto fue actualizado correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "401":
          description: Error por falta de permisos
        "500":
          description: Error interno del servidor

    delete:
      summary: Eliminar un producto por su ID
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "204":
          description: El producto fue eliminado correctamente.
        "401":
          description: Error por falta de permisos
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        stock:
          type: number
          description: Cantidad en stock del producto
        category:
          type: string
          description: Categoría del producto
        _id:
          type: string
          description: ID del producto generado por la base de datos
      example:
        title: Pelota de futbol
        description: Pelota profesional n°5
        code: 1234
        price: 1500
        thumbnail: url
        stock: 100
        category: Futbol
        _id: 

    ProductInput:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: number
          description: Codigo del articulo
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        stock:
          type: number
          description: Cantidad en stock del producto
        category:
          type: string
          description: Categoría del producto
      required:
        - title
        - description
        - price
        - thumbnail
        - stock
        - category
